// 2024_add_title_to_snippets.ts
import { Knex } from 'knex';

/**
 * Migration to add a 'title' column to the 'snippets' table.
 * This column stores the title generated by the LLM for each code snippet.
 */
export async function up(knex: Knex): Promise<void> {
  // Ensure the column does not already exist (Knex's schema builder handles this safely)
  const exists = await knex.schema.hasColumn('snippets', 'title');
  if (!exists) {
    await knex.schema.alterTable('snippets', (table) => {
      table.string('title', 255).notNullable().defaultTo('Untitled');
    });
  }
}

export async function down(knex: Knex): Promise<void> {
  const exists = await knex.schema.hasColumn('snippets', 'title');
  if (exists) {
    await knex.schema.alterTable('snippets', (table) => {
      table.dropColumn('title');
    });
  }
}
